apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-order.name" . }}
  labels:
    {{- include "helm-order.labels" . | nindent 4 }}
spec:
  type: {{ .Values.deploy.serviceType }}
  ports:
    {{- tpl (toYaml .Values.deploy.ports) . | nindent 4 }}
  selector:
    {{- include "helm-order.selectorLabels" . | nindent 4 }}
