apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "helm-prod.name" . }}
  labels:
    {{- include "helm-prod.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "helm-prod.name" . }}
  port:
    targetPort: {{ tpl .Values.route.targetPort . }}
