image:
  name: product-service
  pullPolicy: Always
  tag: latest

build:
  enabled: true
  uri: https://github.com/malam84/helm-quarkus-microservices-ocp4.git
  ref: main
  contextDir: /product-service
  mode: jvm
  jvm:
    imageStreamTag: 
      name: java:openjdk-11-el7
      useReleaseNamespace: false
      namespace: openshift
  output:
    kind: ImageStreamTag
    pushSecret:
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: "1"
      memory: 1Gi

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

route:
  enabled: true
  targetPort: http
  tls: 
    enabled: false

deploy:
  replica: 1
  resources:
    limits:
      cpu: "1"
      memory: 256Mi
    requests:
      cpu: "1"
      memory: 256Mi
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  livenessProbe:
    tcpSocket:
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http
      
